name: .NET

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: 5.0.x
#    - name: Restore dependencies
#      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Pack
    #/p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg 
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push Package
      run: dotnet nuget push Framework.Selenium.${VERSION}.nupkg --no-symbols --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
#    - name: Publish
#      id: publish_nuget
#      uses: brandedoutcast/publish-nuget@v2.5.5
#      with:
#        PACKAGE_NAME: Framework.Automation
#        PROJECT_FILE_PATH: iEmosoft_TestExecutioner/TestAutomation.csproj
#        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
